### ISSUE TITLE
Not working when submit

### ISSUE THREAD

**Issue by Mored4u** [robiso/contact-form#7]
My website: [sec-q8.com](https://sec-q8.com/contact-us-%D8%AA%D9%88%D8%A7%D8%B5%D9%84-%D9%85%D8%B9%D9%86%D8%A7/)
Using: WonderCMS 3.2.0
Subject: get an error when submitting?

This is my Arabic ini file, incloud config file.

![image](https://user-images.githubusercontent.com/5413459/149937600-bd18e49a-2575-40f6-bca3-a02532aed35d.png)
![image](https://user-images.githubusercontent.com/5413459/149937622-58f7b814-f47f-4106-878d-38a2dee588af.png)

[Contact form v3.0.0.zip](https://github.com/robiso/contact-form/files/7889013/Contact.form.v3.0.0.zip)

**Comment by robiso** [comment]
@Mored4u I just tested out with your configuration files and it works as expected.
I receive the message: تم ارسال الرسالة بنجاح. - which google translate says it's "sent successfully".

I also receive the email when trying to send it.
[contact-form.zip](https://github.com/robiso/contact-form/files/7891218/contact-form.zip)

1. Can you try the above .zip file?
- Rename your current contact-form plugin to contact-form2 (to back it up).
- Upload contact-form that I attached above and upload/unzip it to your plugins folder.

2. What is your server configuration:
- PHP version?
- Apache/NGINX server type?

**Comment by Mored4u** [comment]
1) I get the same error after uploading your attached file

![image](https://user-images.githubusercontent.com/5413459/150269915-730e8e6f-d6e4-4dfe-90f7-29979feeed37.png)

2) PHP 7.3.27

Using Microsoft Azure - App Service (Operating System Linux) >> I think custom container

![image](https://user-images.githubusercontent.com/5413459/150270283-bd705a6f-489c-4377-b397-4a48468cda9b.png)

![image](https://user-images.githubusercontent.com/5413459/150270587-6b27d7f6-b142-4c4c-84f7-8d710c6f5fa7.png)

![image](https://user-images.githubusercontent.com/5413459/150271002-230c2361-b685-4cff-809e-ae34281136d3.png)

Note: **may be due to type of server (Azure Web App Service)**

**Comment by Mored4u** [comment]
U can try to log in using the below info:

https://sec-q8.com/Admin
Pass: 123KDDmm

**Comment by robiso** [comment]
@Mored4u that is odd.

I've tried searching for similar issues on stackoverflow, do you maybe know more about domain authentication?
https://stackoverflow.com/questions/65289150/weird-behavior-when-using-contact-form-in-azure-app-service-to-send-email-throug 

Another possible issue is the mail server issues or not being correctly set up, is there any way you can reach out to Azure support to see if there's anything else you need to setup for this to work?

It would be also interesting to see if any other contact form would work on your server.

**Comment by Mored4u** [comment]
I will close this issue, due to no solution for now.

I tried all previous solution but not working for me, I think the problem from Azure Web Service.

Need Microsoft Help !

**Comment by robiso** [comment]
@Mored4u please post back if you get an answer.

**Comment by Mored4u** [comment]
OK
